objects/Account.object
<CustomObject>
    <fields>
        <fullName>AutorabitExtId__c</fullName>
        <description>External Id created by AutoRABIT</description>
        <externalId>true</externalId>
        <label>AutorabitExtId__c</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AutorabitExtId__c</fullName>
        <description>External Id created by AutoRABIT</description>
        <externalId>true</externalId>
        <label>AutorabitExtId__c</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <description>Invoice Number from accounting</description>
        <externalId>true</externalId>
        <inlineHelpText>Invoice Number from accounting</inlineHelpText>
        <label>Invoice Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type_New_Renewal_Upsell__c</fullName>
        <inlineHelpText>Its mandatory to update the type of Opportunity</inlineHelpText>
        <label>Oppty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Downsell</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Subscription_Start_Date__c</field>
                <operation>greaterThan</operation>
                <valueField>Opportunity.Subscription_Start_Date__c</valueField>
            </filterItems>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Closed Won</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Previous Opportunity)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subs_Activation_Email_Sent__c</fullName>
        <description>Date time the subs activation email was sent. Will be blank if before 8/26/2021</description>
        <label>Subs Activation Email Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Is this an annual subscription? If not, please enter the number of months</inlineHelpText>
        <label># of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Months_for_Subs_Activation__c</fullName>
        <label># of Months for Subs Activation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <description>Annualized Total Price (Sales Price * Quantity)</description>
        <formula>TotalPrice * 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Price * 12</inlineHelpText>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AutorabitExtId__c</fullName>
        <description>External Id created by AutoRABIT</description>
        <externalId>true</externalId>
        <label>AutorabitExtId__c</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Given__c</fullName>
        <description>Reduced List Price in %</description>
        <formula>1 - (UnitPrice  /  ListPrice)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Reduced List Price in %</inlineHelpText>
        <label>Discount Given (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_this_PS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this PS?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>This field is mapped to &apos;Product Family&apos; in Product and gets updated via a flow.</description>
        <label>Product Family</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Revenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <description>Contract period</description>
        <inlineHelpText>If this is NOT an annual subs, please enter the number of Months.</inlineHelpText>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>AutorabitExtId__c</fullName>
        <description>External Id created by AutoRABIT</description>
        <externalId>true</externalId>
        <label>AutorabitExtId__c</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AutorabitExtId__c</fullName>
        <description>External Id created by AutoRABIT</description>
        <externalId>true</externalId>
        <label>AutorabitExtId__c</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RenewalOpportunityFactory.cls
public class RenewalOpportunityFactory {
    public static void createRenewalOpp(List<Opportunity> oldOpp){
        Opportunity renewalOpp = oldOpp[0].clone(false,false,false,false);
        renewalOpp.Subscription_Start_Date__c=renewalOpp.Subscription_End_Date__c.addDays(1);
        renewalOpp.Subscription_End_Date__c=renewalOpp.Subscription_End_Date__c.addYears(1);
        renewalOpp.CloseDate=oldOpp[0].Subscription_End_Date__c;
        renewalOpp.StageName='Qualify';
        renewalOpp.Probability=15;
        renewalOpp.Previous_Opportunity__c=oldOpp[0].Id;
        renewalOpp.Opportunity_Type_New_Renewal_Upsell__c='Renewal';
        renewalOpp.of_Months_for_Subs_Activation__c='12';
        renewalOpp.Invoice_Number__c=null;
        renewalOpp.Subs_Activation_Email_Sent__c=null;
        renewalOpp.Name = renewalOpp.Account.Name + ' Renewal ' + renewalOpp.Subscription_Start_Date__c.format();
        renewalOpp.ContactId=oldOpp[0].ContactId;
        insert renewalOpp; 
        
                List<OpportunityContactRole> oldOCRs = new List<OpportunityContactRole>([SELECT ContactId,CreatedById,CreatedDate,CurrencyIsoCode,Id,IsDeleted,IsPrimary,LastModifiedById,LastModifiedDate,OpportunityId,Role,SystemModstamp FROM OpportunityContactRole
WHERE OpportunityId=:oldOpp[0].Id AND IsDeleted=false
]);
         List<OpportunityContactRole> ocrToInsert = new List<OpportunityContactRole>();
        for(OpportunityContactRole o : oldOCRs){
            OpportunityContactRole newOCR = o.clone(false,false,false,false);
            newOCR.OpportunityId=renewalOpp.Id;
            ocrToInsert.add(newOCR);
            //insert newOCR;
        }
        insert ocrToInsert;
        
        List<OpportunityLineItem> oldOLIs = new List<OpportunityLineItem>([SELECT Annual_Revenue__c,AutorabitExtId__c,CreatedById,CreatedDate,CurrencyIsoCode,Description,Discount,Discount_Given__c,Id,IsDeleted,Is_this_PS__c,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,of_Months__c,OpportunityId,PricebookEntryId,Product2Id,ProductCode,ProductFamily__c,Quantity,Recurring_Revenue__c,ServiceDate,SortOrder,Subtotal,SystemModstamp,UnitPrice FROM OpportunityLineItem
WHERE OpportunityId=:oldOpp[0].Id AND PricebookEntry.IsActive=true
and Recurring_Revenue__c=true and Product2Id != '01t0K000006lGeHQAU' AND PRODUCT2.Family != 'Professional Services - Restricted']);
        List<OpportunityLineItem> oliToInsert = new List<OpportunityLineItem>();
        for(OpportunityLineItem o : oldOLIs){
            OpportunityLineItem newOLI = o.clone(false,false,false,false);
            newOLI.OpportunityId=renewalOpp.Id;
            newOLI.UnitPrice=newOLI.UnitPrice*1.05;
            newOLI.of_Months__c=12;
            oliToInsert.add(newOLI);
            //insert newOLI;
        }
        insert oliToInsert; 
        
    }
}