objects/Author__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Noida</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AuthorHandler.cls
public class AuthorHandler {
    public static void insertAuthor(String authorName, String location) {
        try {
            Author__c newAuthor = new Author__c();
            newAuthor.Name = authorName;
            newAuthor.Location__c = location;
            
            insert newAuthor;
            System.debug('Author record inserted successfully: ' + newAuthor.Id);
        } catch (Exception e) {
            System.debug('Error inserting Author: ' + e.getMessage());
        }
    }
}