objects/Book_vin__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Book vin</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books vin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BookHandler.cls
public class BookHandler {
    public static void insertBook(String bookName, Decimal price) {
        try {
            Book_vin__c newBook = new Book_vin__c();
            newBook.Name = bookName;
            newBook.Price__c = price;
            
            insert newBook;
            System.debug('Book record inserted successfully: ' + newBook.Id);
        } catch (Exception e) {
            System.debug('Error inserting Book: ' + e.getMessage());
        }
    }
}