objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Created this field for setting the Automation and Segmentation rules in Pardot.</description>
        <formula>TEXT(Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Populates from respective Account. Edit the account to change it.</inlineHelpText>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suggested_Record_Owner__c</fullName>
        <formula>CASESAFEID(IF(Account.SDR_Owner__r.IsActive = true &amp;&amp; NOT(ISBLANK(Account.SDR_Owner__c)),  Account.SDR_Owner__c,
IF(Account.Owner.IsActive = true &amp;&amp; NOT(ISBLANK(Account.OwnerId)), Account.OwnerId,
&apos;0050K00000BQdcGQAT&apos;)))</formula>
        <label>Suggested Record Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wrong_Owner__c</fullName>
        <formula>(OwnerId &lt;&gt; BLANKVALUE( Account.SDR_Owner__c , Account.OwnerId)) &amp;&amp; (LEFT(OwnerId, 3)=&quot;005&quot;)</formula>
        <label>Wrong Owner</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Suggested_Record_Owner__c</fullName>
        <formula>CASESAFEID(IF(algnlta__Matched_Account__r.SDR_Owner__r.IsActive = true &amp;&amp; NOT(ISBLANK(algnlta__Matched_Account__r.SDR_Owner__c)), algnlta__Matched_Account__r.SDR_Owner__c,
IF(algnlta__Matched_Account__r.Owner.IsActive = true &amp;&amp; NOT(ISBLANK(algnlta__Matched_Account__r.OwnerId)), algnlta__Matched_Account__r.OwnerId,
&apos;0050K00000BQdcGQAT&apos;)))</formula>
        <label>Suggested Record Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wrong_Owner__c</fullName>
        <formula>(OwnerId &lt;&gt; BLANKVALUE( algnlta__Matched_Account__r.SDR_Owner__c , algnlta__Matched_Account__r.OwnerId)) &amp;&amp; (LEFT(OwnerId, 3)=&quot;005&quot;)</formula>
        <label>Wrong Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>algnlta__Matched_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to account used in Align.ly Lead-to-Account Matching.</description>
        <inlineHelpText>The account matched to the lead. Updated by Align.ly and/or manually.</inlineHelpText>
        <label>Matched Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matched Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest {
    @testSetup
    static void setup() {
        Profile[] p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User usr = new User(FirstName='First',
                            LastName='Last',
                            Email = 'puser000@autorabit.com',
                            Username = 'puser000@autorabit.com' + System.currentTimeMillis(),
                            CompanyName = 'TEST',
                            Title = 'title',
                            Alias = 'alias',
                            TimeZoneSidKey = 'America/Los_Angeles',
                            EmailEncodingKey = 'UTF-8',
                            LanguageLocaleKey = 'en_US',
                            LocaleSidKey = 'en_US',
                           ProfileId=p[0].Id);
        insert usr;
        User usr1 = new User(FirstName='First',
                            LastName='Last',
                            Email = 'puser001@autorabit.com',
                            Username = 'puser001@autorabit.com' + System.currentTimeMillis(),
                            CompanyName = 'TEST',
                            Title = 'title',
                            Alias = 'alias',
                            TimeZoneSidKey = 'America/Los_Angeles',
                            EmailEncodingKey = 'UTF-8',
                            LanguageLocaleKey = 'en_US',
                            LocaleSidKey = 'en_US',
                           ProfileId=p[0].Id);
        insert usr1;
        Account acct = new Account(Name='Test Account3');
        insert acct;
        Contact cont = new Contact(LastName='Contact',
                                   FirstName='Test',
                                   AccountId=acct.Id,
                                  LeadSource='ABM');
        insert cont;
        Lead ld1 = new Lead(LastName='Lead',
                                   FirstName='Test',
                                   algnlta__Matched_Account__c=acct.Id,
                           			Company='Test Company',
                          			LeadSource='ABM' );
        insert ld1;
    }
    @isTest static void testAssignAccountToUser(){
        //Perform test
        //Test that account ownership set causes leads and contacts to be assigned to same owner
        List<Account> AcctToUpdate = new List<Account> ([SELECT Id, OwnerId from Account]);
        List<User> UserToUpdate = new List<User> ([Select Id, LastName from User where Email='puser000@autorabit.com' LIMIT 1]);
        AcctToUpdate[0].OwnerId = UserToUpdate[0].Id;
        AcctToUpdate[0].SDR_Owner__c = UserToUpdate[0].Id;
        AcctToUpdate[0].Account_Type__c='ABM';
        Test.startTest();
        update AcctToUpdate;
        List<Lead> LeadsToCheck = new List<Lead>([SELECT OWNERID, Suggested_Record_Owner__c, Wrong_Owner__c, IsConverted, algnlta__Matched_Account__c, LastActivityDate FROM LEAD]);
		system.debug('lead owner ' + LeadsToCheck[0].OwnerId + ' ' + LeadsToCheck[0].Suggested_Record_Owner__c + ' ' + LeadsToCheck[0].Wrong_Owner__c + ' ' + LeadsToCheck[0].IsConverted + ' algnlta__Matched_Account__c ' + LeadsToCheck[0].algnlta__Matched_Account__c + ' LastActivityDate ' + LeadsToCheck[0].LastActivityDate);
        List<Contact> ContactsToCheck = new List<Contact>([SELECT OWNERID FROM Contact]);
        Test.stopTest();
		system.debug('contact owner ' + ContactsToCheck[0].OwnerId);
        system.debug('AcctToUpdate[0].OwnerId ' + AcctToUpdate[0].OwnerId);
        
        //ContactOwnerFixer and LeadOwnerFixer are batchable now, so I'm commenting out these asserts. Each needs to be tested in its own test class. The batchable methods cannot finish here.
		//System.assertEquals(1,[Select count() from Contact WHERE OwnerId=:AcctToUpdate[0].OwnerId]);  
		//System.assertEquals(1,[Select count() from Lead WHERE OwnerId=:AcctToUpdate[0].OwnerId]);
        //Test that account ownership  update causes Last Owner and Last Owner Change Date to be updated.
        List<User> UserToUpdate1 = new List<User> ([Select Id, LastName from User where Email='puser001@autorabit.com' LIMIT 1]);
        AcctToUpdate[0].OwnerId = UserToUpdate1[0].Id;
        update AcctToUpdate;
        System.assertEquals(1,[Select count() from Account WHERE Last_Owner__c=:UserToUpdate[0].Id]);
    }
}