objects/Customer__c.object
<CustomObject>
    <description>A customer that is signed up with AutoRABIT</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Amount__c.object
<CustomObject>
    <description>Amount required</description>
    <label>Loan Amount</label>
    <nameField>
        <label>Loan Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>App_number__c</fullName>
        <label>App number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>this is to check status</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>IN PROGRESS</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>NOT AVAILABLE</fullName>
                </value>
                <value>
                    <fullName>LOST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Applications</relationshipLabel>
        <relationshipName>Loan_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interest_Amount__c</fullName>
        <label>Interest Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoanApplicationHelper.cls
public with sharing class LoanApplicationHelper {
    public class LoanApplicationWrapper {
        public String appNumber { get; set; }
        public String approvalStatus { get; set; }
        public Id customerId { get; set; }
        public Decimal interestAmount { get; set; }
        public Decimal interestRate { get; set; }
        public Decimal loanAmount { get; set; }
        public String currencyIsoCode { get; set; }
    }
 
    public static List<LoanApplicationWrapper> getLoanApplications() {
        List<LoanApplicationWrapper> loanList = new List<LoanApplicationWrapper>();
 
        for (Loan_Application__c loan : [SELECT App_number__c, Approval_Status__c, Customer__c,
                                          Interest_Amount__c, Interest_Rate__c, Loan_Amount__c, CurrencyIsoCode
                                          FROM Loan_Application__c]) {
            LoanApplicationWrapper wrapper = new LoanApplicationWrapper();
            wrapper.appNumber = loan.App_number__c;
            wrapper.approvalStatus = loan.Approval_Status__c;
            wrapper.customerId = loan.Customer__c;
            wrapper.interestAmount = loan.Interest_Amount__c;
            wrapper.interestRate = loan.Interest_Rate__c;
            wrapper.loanAmount = loan.Loan_Amount__c;
            wrapper.currencyIsoCode = loan.CurrencyIsoCode;
 
            loanList.add(wrapper);
        }
        return loanList;
    }
 
    public static void updateLoanApplication(Id loanId, String approvalStatus, Decimal loanAmount) {
        Loan_Application__c loan = [SELECT Id, Approval_Status__c, Loan_Amount__c FROM Loan_Application__c WHERE Id = :loanId LIMIT 1];
        loan.Approval_Status__c = approvalStatus;
        loan.Loan_Amount__c = loanAmount;
        update loan;
      
       
    }
}