objects/Customer__c.object
<CustomObject>
    <description>A customer that is signed up with AutoRABIT</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Amount__c.object
<CustomObject>
    <description>Amount required</description>
    <label>Loan Amount</label>
    <nameField>
        <label>Loan Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>this is to check status</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>IN PROGRESS</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>NOT AVAILABLE</fullName>
                </value>
                <value>
                    <fullName>LOST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Applications</relationshipLabel>
        <relationshipName>Loan_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interest_Amount__c</fullName>
        <label>Interest Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoanApplicationHelperTest.cls
@isTest
public class LoanApplicationHelperTest {
    @testSetup
    static void setupTestData() {
        // Create a test Account
       //List<Account> acc = new List<Account>(Name = 'Test Customer');
        //insert acc; // Insert account first
 
        // Create a Loan Application record
        Loan_Application__c loan = new Loan_Application__c(
            Approval_Status__c = 'Pending',
           // Customer__c = acc.Id, // Associate Loan Application with created Account
            Interest_Amount__c = 5000,
            Interest_Rate__c = 5,
            Loan_Amount__c = 100000
        );
        insert loan; // Insert Loan Application record
    }
 
    @isTest
    static void testGetLoanApplications() {
        Test.startTest();
        List<LoanApplicationHelper.LoanApplicationWrapper> loans = LoanApplicationHelper.getLoanApplications();
        Test.stopTest();
 
        // Assert that loan applications were retrieved
        System.assert(loans.size() > 0, 'Loan applications should be retrieved');
    }
 
    @isTest
    static void testUpdateLoanApplication() {
        // Fetch the Loan Application record
        Loan_Application__c loan = [SELECT Id FROM Loan_Application__c LIMIT 1];
 
        Test.startTest();
        LoanApplicationHelper.updateLoanApplication(loan.Id, 'Approved', 120000);
        Test.stopTest();
 
        // Retrieve updated record
        Loan_Application__c updatedLoan = [SELECT Approval_Status__c, Loan_Amount__c FROM Loan_Application__c WHERE Id = :loan.Id];
 
        // Assertions
        System.assertEquals('Approved', updatedLoan.Approval_Status__c, 'Approval status should be updated');
        System.assertEquals(120000, updatedLoan.Loan_Amount__c, 'Loan amount should be updated');
    }
}