objects/Employee_c__c.object
<CustomObject>
    <fields>
        <fullName>Emp_Email__c</fullName>
        <label>Emp Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmployeeServiceTest.cls
@isTest
public class EmployeeServiceTest {
    @isTest
    static void testGetHighSalaryEmployees() {
        Employee_c__c emp = new Employee_c__c(Name='John Doe', Emp_Email__c='john@example.com', Salary__c=120000);
        insert emp;

        Test.startTest();
        List<Employee_c__c> result = EmployeeService.getHighSalaryEmployees(100000);
        Test.stopTest();

        System.assertEquals(1, result.size());
    }
}