objects/game__c.object
<CustomObject>
    <fields>
        <fullName>indoor_games__c</fullName>
        <label>indoor games</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>chess</fullName>
                </value>
                <value>
                    <fullName>badminton</fullName>
                </value>
                <value>
                    <fullName>table tennis</fullName>
                </value>
                <value>
                    <fullName>carrom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>game</label>
    <nameField>
        <label>game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GameManager.cls
public class GameManager {
// Method to retrieve games marked as "Indoor"
    public static List<Game__c> getIndoorGames() {
        return [SELECT Id, Name, Indoor_Games__c FROM Game__c WHERE Indoor_Games__c = 'Indoor'];
    }

    // Method to create a new game record
    public static Id createGame(String name, String gameType) {
        Game__c newGame = new Game__c(
            Name = name,
            Indoor_Games__c = gameType
        );
        insert newGame;
        return newGame.Id;
    }
}