objects/Institute__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Name__c</fullName>
        <label>Alias Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Institute</label>
    <nameField>
        <label>Institute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutes</pluralLabel>
    <recordTypes>
        <fullName>institute</fullName>
        <active>true</active>
        <label>institute</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InstituteEmailSender.cls
public class InstituteEmailSender {

    // Method to send email to the email address entered in the Email__c field
    public static void sendEmail(Institute__c instituteRecord) {
        // Get the email address from the Email__c field of the Institute__c record
        String recipientEmail = instituteRecord.Email__c;
        
        // Check if the email address is valid
        if (recipientEmail != null && recipientEmail != '') {
            // Create a new instance of SingleEmailMessage
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            // Set the recipient email address
            mail.setToAddresses(new String[] { recipientEmail });
            
            // Set the email subject
            mail.setSubject('Welcome to the Institute');
            
            // Set the email body (you can customize this message)
            mail.setPlainTextBody('Dear ' + instituteRecord.Alias_Name__c + ',\n\n'
                                  + 'Thank you for registering with our institute. We are excited to have you on board.\n\n'
                                  + 'Best regards,\nThe Institute Team');
            
            // Send the email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}