objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Suggested_Record_Owner__c</fullName>
        <formula>CASESAFEID(IF(algnlta__Matched_Account__r.SDR_Owner__r.IsActive = true &amp;&amp; NOT(ISBLANK(algnlta__Matched_Account__r.SDR_Owner__c)), algnlta__Matched_Account__r.SDR_Owner__c,
IF(algnlta__Matched_Account__r.Owner.IsActive = true &amp;&amp; NOT(ISBLANK(algnlta__Matched_Account__r.OwnerId)), algnlta__Matched_Account__r.OwnerId,
&apos;0050K00000BQdcGQAT&apos;)))</formula>
        <label>Suggested Record Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>algnlta__Matched_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to account used in Align.ly Lead-to-Account Matching.</description>
        <inlineHelpText>The account matched to the lead. Updated by Align.ly and/or manually.</inlineHelpText>
        <label>Matched Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matched Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/LeadOwnerFixerTest.cls
@IsTest
public class LeadOwnerFixerTest {
    @testSetup
    static void setup() {
        List<Lead> leads = new List<Lead>();
        Account acct = new Account(Name='Test Account3');
        insert acct;
        // insert 4 leads
        for (Integer i=0;i<4;i++) {
            leads.add(new Lead(firstname='first'+i,
                lastname='last'+i,algnlta__Matched_Account__c=acct.Id, Company='Test Account'));
        }
        insert leads;
    }
    @isTest static void test() {
        Test.startTest();
        LeadOwnerFixer uca = new LeadOwnerFixer([SELECT Name, Id, OwnerId, Suggested_Record_Owner__c FROM LEAD]);
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(4, [select count() from Lead where OwnerId != null]);
    }
}