objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Type_New_Renewal_Upsell__c</fullName>
        <inlineHelpText>Its mandatory to update the type of Opportunity</inlineHelpText>
        <label>Oppty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Downsell</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Is this an annual subscription? If not, please enter the number of months</inlineHelpText>
        <label># of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Months_for_Subs_Activation__c</fullName>
        <label># of Months for Subs Activation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Accounting_Bin_Override__c</fullName>
        <description>Fill in if a value different than the Product2 Value is needed. This is usually necessary for the One Time Discount Product.</description>
        <inlineHelpText>Fill in if a value different than the Product2 Value is needed. This is usually necessary for the One Time Discount Product.</inlineHelpText>
        <label>Accounting Bin Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CodeScan</fullName>
                </value>
                <value>
                    <fullName>Implementation Revenue</fullName>
                </value>
                <value>
                    <fullName>Record Migrator</fullName>
                </value>
                <value>
                    <fullName>Subscriptions</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Vault</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <description>Contract period</description>
        <inlineHelpText>If this is NOT an annual subs, please enter the number of Months.</inlineHelpText>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Non-recurring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/schedAccountCurrentMetricsDailyTest.cls
@IsTest
public class schedAccountCurrentMetricsDailyTest {
	@testSetup
  	static void setup() {
        //Test data setup create product, opportunity, opportunity products
        Account acct = new Account(Name='Test Account3');
        insert acct;
        Contact cont = new Contact(LastName='Contact',
                                   FirstName='Test',
                                  AccountId=acct.Id);
        insert cont;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today(),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'New Logo',
                                         Pricebook2Id=standardPricebook.id,
                                         Subscription_End_Date__c=DATE.TODAY().addmonths(12).toStartOfMonth().adddays(-1),
                                         Subscription_Start_Date__c=DATE.TODAY(), 
                                         of_Months_for_Subs_Activation__c='12',
                                         ContactId=cont.Id);
        insert opp;
        OpportunityContactRole ocr = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='First Contact');
        insert ocr;
        OpportunityContactRole ocrTech = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='Technical Contact');
        insert ocrTech;
        OpportunityContactRole ocrBusiness = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='Business Contact');
        insert ocrBusiness;
        Product2 prod = new Product2(Name='Test Product', Product_Type__c='Recurring');
        insert prod;
        PricebookEntry pbe=new PricebookEntry(Pricebook2Id=standardPricebook.Id, Product2Id=prod.Id, UnitPrice=1, IsActive = true);
        insert pbe;        
    	system.debug(opp.Id);
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10);
        OpportunityLineItem oli1 = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10, Accounting_Bin_Override__c='CodeScan');
        OpportunityLineItem oli2 = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10, Accounting_Bin_Override__c='Record Migrator');
        OpportunityLineItem oli3 = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10, Accounting_Bin_Override__c='Support');
        OpportunityLineItem oli4 = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10, Accounting_Bin_Override__c='Vault');
        insert oli;
        insert oli1;
        insert oli2;
        insert oli3;
        insert oli4;
        List<Opportunity> oppToWon = [SELECT Id, StageName from Opportunity where Name = 'Test Account3 Opportunity' LIMIT 1];
        oppToWon[0].StageName = 'Closed Won';
        Update oppToWon;
    }
    @IsTest static void SetARRLastFullMonthTest(){
    	// Dummy CRON expression: midnight on March 15.
   		// Because this is a test, job executes
    	// immediately after Test.stopTest().
        String CRON_EXP = '0 0 0 15 3 ? 2029';
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP,
            new schedAccountCurrentMetricsDaily());
        // Stopping the test will run the job synchronously
        Test.stopTest();
        // Now that the scheduled job has executed,
        // check that Parent_of_Customer__c has been changed to false
        System.assertEquals(1,[SELECT Count() from Account where ARR_End_of_Month__c=600]);
    }
       
}