objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Type_New_Renewal_Upsell__c</fullName>
        <inlineHelpText>Its mandatory to update the type of Opportunity</inlineHelpText>
        <label>Oppty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Downsell</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Is this an annual subscription? If not, please enter the number of months</inlineHelpText>
        <label># of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <description>Contract period</description>
        <inlineHelpText>If this is NOT an annual subs, please enter the number of Months.</inlineHelpText>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/ProductsPerAccountFactoryTest.cls
@IsTest
public class ProductsPerAccountFactoryTest {
    @isTest static void testProductsPerAccountFactory(){
        //Test data setup create product, opportunity, opportunity products
        Account acct = new Account(Name='Test Account');
        insert acct;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today().addMonths(1),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'Renewal',
                                         Pricebook2Id=standardPricebook.id,
                                         Subscription_End_Date__c=Date.newInstance(2022, 9, 30),
                                         Subscription_Start_Date__c=Date.newInstance(2021, 10, 1));
        insert opp;
        Product2 prod = new Product2(Name='Test Product');
        insert prod;
        PricebookEntry pbe=new PricebookEntry(Pricebook2Id=standardPricebook.Id, Product2Id=prod.Id, UnitPrice=1, IsActive = true);
        insert pbe;
        system.debug(opp.Id);
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=2, Product2Id=prod.Id, UnitPrice=7);
        insert oli;
        //run test
        ProductsPerAccountFactory ppaf1 = new ProductsPerAccountFactory();
        	ppaf1.AcctId=acct.id;
        	ppaf1.DateToCheck=opp.Subscription_Start_Date__c;
        ppaf1.getProductsPerAccount();
    }
}