objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opt_Out_Date__c</fullName>
        <description>Date the customer exercised the opt out clause of the contract for this opportunity. Only fill this out if the opportunity was Closed Won.</description>
        <inlineHelpText>Date the customer exercised the opt out clause of the contract for this opportunity. Only fill this out if the opportunity was Closed Won.</inlineHelpText>
        <label>Opt Out Exercise Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Item_End_Date__c</fullName>
        <formula>IF(ISBLANK(Item_Start_Date__c),  Opportunity.Subscription_End_Date__c ,  ADDMONTHS(Item_Start_Date__c, of_Months__c)-1)</formula>
        <label>Item End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_Start_Date__c</fullName>
        <description>Start date of this opportunity line item if it differs from the start date of the full opportunity, or if the number of months for this product differs from the full opportunity. This only applies for recurring products.</description>
        <inlineHelpText>Start date of this opportunity line item if it differs from the start date of the full opportunity, or if the number of months for this product differs from the full opportunity. This only applies for recurring products.</inlineHelpText>
        <label>Item Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

classes/ProductsPerAccountFactory.cls
public without sharing class ProductsPerAccountFactory {
    public String AcctId {get;set;}
    public Date DateToCheck {get;set;}
    List<AggregateResult> Records;

    //public void setProductsPerAccount(string theAcctId){
     //string Acct_Id =  '0010K00002UoYCRQA3'; 
       // string AcctId=theAcctId;
   // }
	
	public List<AggregateResult> getProductsPerAccount(){
        //Date DateToCheck = Date.valueOf('2020-01-01');
        //String Acct_Id = '0010K00002UoYCRQA3';
        Records=[select Product2.Name pn, SUM(Quantity) q from OpportunityLineItem where
                  Opportunity.AccountId=:AcctId AND
                  Opportunity.STAGENAME='Closed Won'
                   AND  OPPORTUNITY.OPT_OUT_DATE__C =NULL
                 AND ((Item_Start_Date__c != NULL AND Item_Start_Date__c <= :DateToCheck) OR (Item_Start_Date__c = NULL AND Opportunity.Subscription_Start_Date__c  <= :DateToCheck))
            	 AND Item_End_Date__c >= :DateToCheck
                 and Product2Id != '01t0K000006lGeHQAU'
                 GROUP BY PRODUCT2.NAME
                 ORDER BY PRODUCT2.NAME];
        //System.Debug(Records);
        //System.Debug(Records.size());
        Return Records;
	}
}