objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ARR_Last_Full_Month_of_Opp__c</fullName>
        <description>ARR Last Full Month of Opp</description>
        <inlineHelpText>ARR Last Full Month of Opp</inlineHelpText>
        <label>ARR Renewable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Is this an annual subscription? If not, please enter the number of months</inlineHelpText>
        <label># of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Months_for_Subs_Activation__c</fullName>
        <label># of Months for Subs Activation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <description>Annualized Total Price (Sales Price * Quantity)</description>
        <formula>TotalPrice * 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Price * 12</inlineHelpText>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_End_Date__c</fullName>
        <formula>IF(ISBLANK(Item_Start_Date__c),  Opportunity.Subscription_End_Date__c ,  ADDMONTHS(Item_Start_Date__c, of_Months__c)-1)</formula>
        <label>Item End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_Start_Date__c</fullName>
        <description>Start date of this opportunity line item if it differs from the start date of the full opportunity, or if the number of months for this product differs from the full opportunity. This only applies for recurring products.</description>
        <inlineHelpText>Start date of this opportunity line item if it differs from the start date of the full opportunity, or if the number of months for this product differs from the full opportunity. This only applies for recurring products.</inlineHelpText>
        <label>Item Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recurring_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Revenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <description>Contract period</description>
        <inlineHelpText>If this is NOT an annual subs, please enter the number of Months.</inlineHelpText>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/AccountingValueFactory.cls
public class AccountingValueFactory {
    public static void SetARRLastFullMonth(List<Opportunity> oppsToUpdate){
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        for(Opportunity o:oppsToUpdate){
            AggregateResult arMD = [select max(Item_End_Date__c), max(of_months__c), min(Item_Start_Date__c) from OpportunityLineItem where Recurring_Revenue__c=true and OpportunityId=:o.Id];
            Date MaxItemEndDate = (Date)arMD.get('expr0');
            Decimal MaxItemofMonths = (Decimal)arMD.get('expr1');
            Date MinItemStartDate = (Date)arMD.get('expr2');
            if(o.Subscription_Start_Date__c==null){o.Subscription_Start_Date__c = MinItemStartDate==null ? o.CloseDate + 1 : MinItemStartDate;}
            if(o.Subscription_End_Date__c==null){o.Subscription_End_Date__c = MaxItemEndDate==null ? o.CloseDate.addMonths(Integer.valueOf(String.valueof(MaxItemofMonths))) : MaxItemEndDate;}
            if(string.isBlank(o.of_Months_for_Subs_Activation__c)){o.of_Months_for_Subs_Activation__c = String.valueof(o.Subscription_Start_Date__c.monthsBetween(o.Subscription_End_Date__c));}
            if(MaxItemEndDate != null){
                MaxItemEndDate = MaxItemEndDate.toStartOfMonth();
                AggregateResult ar = [select SUM(Annual_Revenue__c), OpportunityId
                                      from OpportunityLineItem where Recurring_Revenue__c=true 
                                      and OpportunityId =:o.Id
                                      and ((Item_End_Date__c >= :MaxItemEndDate) OR (Item_Start_Date__c = null))
                                      GROUP BY OpportunityId
                                     ];  
                Decimal total = Decimal.valueOf(String.valueOf(ar.get('expr0')));
                opportunitiesToUpdate.add(new Opportunity(
                    Id = String.valueOf(ar.get('OpportunityId')),ARR_Last_Full_Month_of_Opp__c = total,
                Subscription_Start_Date__c=o.Subscription_Start_Date__c, Subscription_End_Date__c = o.Subscription_End_Date__c,
                of_Months_for_Subs_Activation__c=o.of_Months_for_Subs_Activation__c)
                                         );
            } else if (MaxItemofMonths!=null){
                AggregateResult ar = [select SUM(Annual_Revenue__c), COUNT(Id), OpportunityId
                                      from OpportunityLineItem where Recurring_Revenue__c=true 
                                      and OpportunityId =:o.Id
                                      GROUP BY OpportunityId
                                     ];
                Decimal total = 0;
                if(Decimal.valueOf(String.valueOf(ar.get('expr0')))!=null){
                           total = Decimal.valueOf(String.valueOf(ar.get('expr0')));
                }
                            opportunitiesToUpdate.add(new Opportunity(
                    Id = o.Id,ARR_Last_Full_Month_of_Opp__c = total,
                Subscription_Start_Date__c=o.Subscription_Start_Date__c, Subscription_End_Date__c = o.Subscription_End_Date__c,
                of_Months_for_Subs_Activation__c=o.of_Months_for_Subs_Activation__c)
                                         );
            }
            	else{Decimal total = 0;
                opportunitiesToUpdate.add(new Opportunity(
                    Id = o.Id,ARR_Last_Full_Month_of_Opp__c = total,
                Subscription_Start_Date__c=o.Subscription_Start_Date__c, Subscription_End_Date__c = o.Subscription_End_Date__c,
                of_Months_for_Subs_Activation__c=o.of_Months_for_Subs_Activation__c)
                                         );}
            
            
        } 
        if (!opportunitiesToUpdate.isEmpty()) {
            update opportunitiesToUpdate;
        }
    }
}