objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ARR_Last_Full_Month_of_Opp__c</fullName>
        <description>ARR Last Full Month of Opp</description>
        <inlineHelpText>ARR Last Full Month of Opp</inlineHelpText>
        <label>ARR Renewable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type_New_Renewal_Upsell__c</fullName>
        <inlineHelpText>Its mandatory to update the type of Opportunity</inlineHelpText>
        <label>Oppty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Downsell</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Is this an annual subscription? If not, please enter the number of months</inlineHelpText>
        <label># of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Months_for_Subs_Activation__c</fullName>
        <label># of Months for Subs Activation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <description>Contract period</description>
        <inlineHelpText>If this is NOT an annual subs, please enter the number of Months.</inlineHelpText>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Non-recurring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountingValueFactoryTest.cls
@IsTest
public class AccountingValueFactoryTest {
	@testSetup
  	static void setup() {
        //Test data setup create product, opportunity, opportunity products
        Account acct = new Account(Name='Test Account3');
        insert acct;
        Contact cont = new Contact(LastName='Contact',
                                   FirstName='Test',
                                  AccountId=acct.Id);
        insert cont;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today().addMonths(1),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'New Logo',
                                         Pricebook2Id=standardPricebook.id,
                                         Subscription_End_Date__c=Date.newInstance(2022, 9, 30),
                                         Subscription_Start_Date__c=Date.newInstance(2021, 10, 1), 
                                         of_Months_for_Subs_Activation__c='12',
                                         ContactId=cont.Id);
        insert opp;
        OpportunityContactRole ocr = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='First Contact');
        insert ocr;
        OpportunityContactRole ocrTech = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='Technical Contact');
        insert ocrTech;
        OpportunityContactRole ocrBusiness = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='Business Contact');
        insert ocrBusiness;
        Product2 prod = new Product2(Name='Test Product', Product_Type__c='Recurring');
        insert prod;
        PricebookEntry pbe=new PricebookEntry(Pricebook2Id=standardPricebook.Id, Product2Id=prod.Id, UnitPrice=1, IsActive = true);
        insert pbe;        
    	system.debug(opp.Id);
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10);
        insert oli;
        Opportunity opp2 = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today().addMonths(1),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'New Logo',
                                         Pricebook2Id=standardPricebook.id,
                                         //Subscription_End_Date__c=Date.newInstance(2022, 9, 30),
                                         //Subscription_Start_Date__c=Date.newInstance(2021, 10, 1), 
                                         //of_Months_for_Subs_Activation__c='12',
                                         ContactId=cont.Id);
        insert opp2;
        OpportunityContactRole ocr2 = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp2.Id,
                                                               IsPrimary=true,
                                                               Role='First Contact');
        insert ocr2;
        OpportunityContactRole ocrTech2 = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp2.Id,
                                                               IsPrimary=true,
                                                               Role='Technical Contact');
        insert ocrTech2;
        OpportunityContactRole ocrBusiness2 = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp2.Id,
                                                               IsPrimary=true,
                                                               Role='Business Contact');
        insert ocrBusiness2;
        OpportunityLineItem oli2 = new OpportunityLineItem(OpportunityId=opp2.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10);
        insert oli2;
    }
    @IsTest static void SetARRLastFullMonthTest(){
        List<Opportunity> opportunitiesToUpdate = [SELECT ID, Subscription_Start_Date__c, Subscription_End_Date__c, CloseDate, of_Months_for_Subs_Activation__c FROM OPPORTUNITY];
        Test.startTest();
    	AccountingValueFactory.SetARRLastFullMonth(opportunitiesToUpdate);
    	Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(2, [select count() from Opportunity where ARR_Last_Full_Month_of_Opp__c  = 120]);
    }
}