objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ARR_Amount__c</fullName>
        <description>Some products have a duration that is part of the subscription period. This formula recognizes the ARR across the subscription period evenly. For example if it&apos;s a 24 month duration with one product for 12 months and a different product for 12 months, we cannot count both products ARR for all 12 months. We have to find the Average ARR across the subscription and arrive at the ARR multiplying by 12.</description>
        <formula>(Total_Price_of_Recurring_Products__c/IF(Value(of_Months_for_Subs_Activation__c)&gt;0,Value(of_Months_for_Subs_Activation__c),12))*12
* IF(ISBLANK( Opt_Out_Date__c ),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ARR Amount Monthly Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type_New_Renewal_Upsell__c</fullName>
        <inlineHelpText>Its mandatory to update the type of Opportunity</inlineHelpText>
        <label>Oppty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Downsell</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subs_Activation_Email_Sent__c</fullName>
        <description>Date time the subs activation email was sent. Will be blank if before 8/26/2021</description>
        <label>Subs Activation Email Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Is this an annual subscription? If not, please enter the number of months</inlineHelpText>
        <label># of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Months_for_Subs_Activation__c</fullName>
        <label># of Months for Subs Activation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <description>Contract period</description>
        <inlineHelpText>If this is NOT an annual subs, please enter the number of Months.</inlineHelpText>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Non-recurring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandlerTest.cls
@IsTest
public class OpportunityTriggerHandlerTest {
	@isTest (SeeAllData=false) static void testUpdateOpportunityToClosedWon(){
        //Test data setup create product, opportunity, opportunity products
        Account acct = new Account(Name='Test Account3');
        insert acct;
        Contact cont = new Contact(LastName='Contact',
                                   FirstName='Test',
                                  AccountId=acct.Id);
        insert cont;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today().addMonths(1),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'New Logo',
                                         Pricebook2Id=standardPricebook.id,
                                         Subscription_End_Date__c=Date.newInstance(2022, 9, 30),
                                         Subscription_Start_Date__c=Date.newInstance(2021, 10, 1), 
                                         of_Months_for_Subs_Activation__c='12',
                                         ContactId=cont.Id);
        insert opp;
        OpportunityContactRole ocr = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='First Contact');
        insert ocr;
        OpportunityContactRole ocrTech = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='Technical Contact');
        insert ocrTech;
        OpportunityContactRole ocrBusiness = new OpportunityContactRole(ContactId=cont.Id,
        														OpportunityId=opp.Id,
                                                               IsPrimary=true,
                                                               Role='Business Contact');
        insert ocrBusiness;
        Product2 prod = new Product2(Name='Test Product', Product_Type__c='Recurring');
        insert prod;
        PricebookEntry pbe=new PricebookEntry(Pricebook2Id=standardPricebook.Id, Product2Id=prod.Id, UnitPrice=1, IsActive = true);
        insert pbe;
        system.debug(opp.Id);
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, of_Months__c=12, Product2Id=prod.Id, UnitPrice=10);
        insert oli;
        //system.debug([Select of_Months__c from QuoteLineItem WHERE OpportunityLineItemId = :oli.Id LIMIT 1]);
        Test.startTest();
        Opportunity oppsToUpdate = [SELECT Id, of_Months__c, StageName, Opportunity_ARR_Amount__c,Subs_Activation_Email_Sent__c  from Opportunity where Name='Test Account3 Opportunity' LIMIT 1];
        system.debug('oppsToUpdate.of_Months__c '+oppsToUpdate.of_Months__c);
        system.debug('oppsToUpdate.StageName '+oppsToUpdate.StageName);
        system.debug('oppsToUpdate.Opportunity_ARR_Amount__c ' + oppsToUpdate.Opportunity_ARR_Amount__c);
        system.debug('oppsToUpdate.Subs_Activation_Email_Sent__c ' + oppsToUpdate.Subs_Activation_Email_Sent__c);
        oppsToUpdate.StageName='Closed Won';
        opp.StageName='Closed Won';
        update oppsToUpdate;
        update opp;
       // system.debug('oli.Id '+oli.Id);
        //system.debug('qli.id '+ qli.Id);
        system.debug('oppsToUpdate.of_Months__c '+oppsToUpdate.of_Months__c);
        system.debug('oppsToUpdate.StageName '+oppsToUpdate.StageName);
        system.debug('oppsToUpdate.Opportunity_ARR_Amount__c ' + oppsToUpdate.Opportunity_ARR_Amount__c);
        system.debug('oppsToUpdate.Subs_Activation_Email_Sent__c ' + oppsToUpdate.Subs_Activation_Email_Sent__c);
        //Perform test
        //List<Opportunity> renewalOpp = [SELECT count() FROM Opportunity WHERE StageName='Qualify'];
        //system.debug('renewalOpp[0].Id '+ renewalOpp[0].Id);
        //System.assertEquals(1,[SELECT count() FROM Opportunity WHERE Name='Test Account Renewal 10/1/2022 to 9/30/2023']);
        Test.stopTest();
        System.assertEquals(1,[SELECT count() FROM Opportunity WHERE StageName='Qualify']);
        //Test.stopTest();
    }
}