objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitors__c</fullName>
        <label>Competitors</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Copado</fullName>
                </value>
                <value>
                    <fullName>Flosum</fullName>
                </value>
                <value>
                    <fullName>Gearset</fullName>
                </value>
                <value>
                    <fullName>Jenkins</fullName>
                </value>
                <value>
                    <fullName>Atlassian - Bamboo</fullName>
                    <label>Bamboo</label>
                </value>
                <value>
                    <fullName>Dream factory – Snapshot</fullName>
                    <label>Snapshot</label>
                </value>
                <value>
                    <fullName>Jitterbit</fullName>
                </value>
                <value>
                    <fullName>Odaseva</fullName>
                </value>
                <value>
                    <fullName>Homegrown</fullName>
                </value>
                <value>
                    <fullName>Provar</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>OwnBackup</fullName>
                </value>
                <value>
                    <fullName>GRAX</fullName>
                </value>
                <value>
                    <fullName>Capstorm</fullName>
                </value>
                <value>
                    <fullName>Clayton</fullName>
                </value>
                <value>
                    <fullName>PMD</fullName>
                </value>
                <value>
                    <fullName>SonarQube</fullName>
                </value>
                <value>
                    <fullName>Codacy</fullName>
                </value>
                <value>
                    <fullName>Checkmarx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type_New_Renewal_Upsell__c</fullName>
        <inlineHelpText>Its mandatory to update the type of Opportunity</inlineHelpText>
        <label>Oppty Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Downsell</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A trigger will check this box if someone attaches a file to the opportunity that has the words PO or Order or Signed in it.</description>
        <label>Order Attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentLinkTriggerHandlerTest.cls
@IsTest
public class ContentDocumentLinkTriggerHandlerTest {
	@isTest static void testInsertContentDocumentWithOrderInFileName(){
        //Test data setup create Account, Opportunity, ContentDocument
        Account acct = new Account(Name='Test Account');
        insert acct;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today().addMonths(1),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'New Logo',
                                         Pricebook2Id=standardPricebook.id,
                                         Subscription_End_Date__c=Date.newInstance(2022, 9, 30),
                                         Subscription_Start_Date__c=Date.newInstance(2021, 10, 1),
                                         NextStep='Testing',
                                         Competitors__c='None');
        insert opp;
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the'); 
            
            ContentVersion contentVersion_1 = new ContentVersion(
                Title='Testorder', 
                PathOnClient ='TestOrder.txt',
                VersionData = bodyBlob,
                origin = 'C'
            );
            insert contentVersion_1;
                      
            ContentDocumentLink contentlink = new ContentDocumentLink();
            contentlink.LinkedEntityId = opp.id;
            contentlink.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersion_1.Id].ContentDocumentId;
        	contentlink.ShareType = 'V';
            insert contentlink;
        	system.debug('opp.Id '+opp.Id);
        	system.debug('contentlink.ContentDocumentId '+contentlink.ContentDocumentId);
        	system.debug([SELECT Title FROM ContentVersion WHERE Id =:contentVersion_1.Id]);
        	system.debug([SELECT Title FROM ContentDocument WHERE LatestPublishedVersionId =:contentVersion_1.Id]);
        	system.debug([SELECT Order_Attached__c FROM Opportunity where Id=:contentlink.LinkedEntityId]);
        	system.debug('contentlink.LinkedEntityId '+contentlink.LinkedEntityId);
        
       		List<Opportunity> olis = new List<Opportunity>([SELECT Order_Attached__c FROM Opportunity where Id=:contentlink.LinkedEntityId LIMIT 1]);

            System.assertEquals(true,olis[0].Order_Attached__c);
    }
    	@isTest static void testInsertContentDocumentWithoutOrderInFileName(){
        //Test data setup create Account, Opportunity, ContentDocument
        Account acct = new Account(Name='Test Account');
        insert acct;
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                          StageName='Qualify',
                                          CloseDate=System.today().addMonths(1),
                                          AccountId=acct.Id,
                                          Opportunity_Type_New_Renewal_Upsell__c = 'New Logo',
                                         Pricebook2Id=standardPricebook.id,
                                         Subscription_End_Date__c=Date.newInstance(2022, 9, 30),
                                         Subscription_Start_Date__c=Date.newInstance(2021, 10, 1),
                                         NextStep='Testing',
                                         Competitors__c='None');
        insert opp;
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the'); 
            
            ContentVersion contentVersion_1 = new ContentVersion(
                Title='TestTest', 
                PathOnClient ='TestOrder.txt',
                VersionData = bodyBlob,
                origin = 'C'
            );
            insert contentVersion_1;
                      
            ContentDocumentLink contentlink = new ContentDocumentLink();
            contentlink.LinkedEntityId = opp.id;
            contentlink.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersion_1.Id].ContentDocumentId;
        	contentlink.ShareType = 'V';
            insert contentlink;
        	system.debug('opp.Id '+opp.Id);
        	system.debug('contentlink.ContentDocumentId '+contentlink.ContentDocumentId);
        	system.debug([SELECT Title FROM ContentVersion WHERE Id =:contentVersion_1.Id]);
        	system.debug([SELECT Title FROM ContentDocument WHERE LatestPublishedVersionId =:contentVersion_1.Id]);
        	system.debug([SELECT Order_Attached__c FROM Opportunity where Id=:contentlink.LinkedEntityId]);
        	system.debug('contentlink.LinkedEntityId '+contentlink.LinkedEntityId);
        
       		List<Opportunity> olis = new List<Opportunity>([SELECT Order_Attached__c FROM Opportunity where Id=:contentlink.LinkedEntityId LIMIT 1]);

            System.assertEquals(false,olis[0].Order_Attached__c);
    }
}