objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>To Create and Complete General Task</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskTriggerTest.cls
@isTest
public class TaskTriggerTest {
    @isTest
    static void testOverdueTask() {
        // Create a test user
        User testUser = [SELECT Id, Email FROM User LIMIT 1];
        
        // Create a Task record
        Task__c testTask = new Task__c(
            Name = 'Test Task',
            Assigned_To__c = testUser.Id,
            Due_Date__c = Date.today().addDays(-1),
            Status__c = 'Not Started'
        );
        insert testTask;

        // Query and assert the changes made by the trigger
        Task__c updatedTask = [SELECT Status__c FROM Task__c WHERE Id = :testTask.Id];
        System.assertEquals('Overdue', updatedTask.Status__c);
        //Test EZ commit
    }
}